### PR TITLE
make sure at strong contrasts the multiple refinements are not at the same layer

### PR DESCRIPTION
**Pull request by martinvandriel**

### CODE REVIEW

**Comment by martinvandriel** [comment]
actually I think this will change all meshes slightly. Previously, refinements where always one layer below a discontinuity, which produced unnecessary extra elements. A strange feeling tells me, that this might have been on purpose though, probably related to doubling layers not being allowed at the solid fluid interfaces?

**Comment by sstaehler** [comment]
> A strange feeling tells me, that this might have been on purpose though, probably related to doubling layers not being allowed at the solid fluid interfaces?

Indeed, I added that some time ago (somewhere here aa27dfc558eb2ec941c98fc2837f640738f244ab) to make life a bit easier with Europa-style models (water layer directly above silicate mantle). Hacky, yes.

**Comment by sstaehler** [comment]
Can you rebase it to the latest commit (240a36fdfa642516a11ab0698bf732400de32fb7)?

**Comment by martinvandriel** [comment]
Don't get it, 240a36f was readily there when I pulled your branch...

**Comment by sstaehler** [comment]
On 05/01/17 10:17, Martin van Driel wrote:
> Don't get it, 240a36f was readily there when I pulled your branch...
>
Okay,

solved it. Do you have any ideas for a simple test on whether a mesh is 
fundamentally correct (no gaps, no doubling layers close to boundaries?)

**Pull request merged**
